from lm_results import *
import pickle as p

# turkish
# Get Results (Ordered Inbound 100)
test = ModulateText(turkish_100, language="turkish")
print("Test text created!")
model = NgramModel(test.tokens, alpha=0, n=3)
print("LM setup complete!")
t = LMResultsBaseline(model, test)
t.get_results("LM_n3_(TURKISH)_a0.1_OI_train(100)_test(100).txt")
file = open("LM_n3_(TURKISH)_a0.1_OI_train(100)_test(100)", "wb")
p.dump(model, file)
print("LM created!")

# Get Results (Ordered Inbound 100)
test = ModulateText(turkish_100, language="turkish")
print("Test text created!")
model = NgramModel(test.tokens, alpha=0.1, n=3)
print("LM setup complete!")
t = LMResults(model, test)
t.get_results("LM_n3_(TURKISH)_a0.1_OI_train(100)_test(100).txt")
file = open("LM_n3_(TURKISH)_a0.1_OI_train(100)_test(100)", "wb")
p.dump(model, file)
print("LM created!")

# Get Results (Train Ordered Inbound 90, Test Ordered Inbound 10)
train = ModulateText(turkish_90, language="turkish")
model = NgramModel(test.tokens, alpha=0.1, n=3)
print("LM setup complete!")
test = ModulateText(turkish_10, language="turkish")
print("Test text created!")
t = LMResults(model, test)
t.get_results("LM_n3_(TURKISH)_a0.1_OI_train(90)_test(10).txt")
file = open("LM_n3_(TURKISH)_a0.1_OI_train(100)_test(100)", "wb")
p.dump(model, file)
print("LM created!")

# Get Results (Train Random Outbound 90, Test Random Inbound 10)
train = ModulateText(turkish_90, language="turkish", randomize_across_sentence=True)
model = NgramModel(test.tokens, alpha=0.1, n=3)
print("LM setup complete!")
test = ModulateText(turkish_10, language="turkish", randomize_within_sentence=True)
print("Test text created!")
t = LMResults(model, test)
t.get_results("LM_n3_(TURKISH)_a0.1_R_train(90_o)_test(10_i).txt")
file = open("LM_n3_(TURKISH)_a0.1_R_train(90_o)_test(10_i)", "wb")
p.dump(model, file)
print("LM created!")